---
title: "R-Exercise Week 3, Segementation and Similarity "
output: html_notebook
---

Task 1:

```{r}
library(readr)        
library(dplyr)        
library(ggplot2)      
library(sf)          
library(terra)        
library(lubridate)
library(zoo)

#reading in the data
caro <- read_csv("data/caro60.csv")

#sampling interval is chosen to be 5 minutes.

caro <- caro %>%
  mutate(
    n_minus3 = sqrt((lag(E,3)-E)^2+(lag(N,3)-N)^2),
    n_minus2 = sqrt((lag(E,2)-E)^2+(lag(N,2)-N)^2), #distance to pos -2 minutes
    n_minus1 = sqrt((lag(E,1)-E)^2+(lag(N,1)-N)^2),
    n_plus1 = sqrt((E-lead(E,1))^2+(N-lead(N,1))^2),
    n_plus2 = sqrt((E-lead(E,2))^2+(N-lead(N,2))^2),
    n_plus3 = sqrt((E-lead(E,3))^2+(N-lead(N,3))^2)
  ) %>%
  
  rowwise() %>%
  
  mutate(
    stepMean = mean(c(n_minus2, n_minus1, n_minus3, n_plus1, n_plus2, n_plus3))
  ) %>%
  
  ungroup()
  
```

Task 2

```{r}
  
hist(x = caro$stepMean, breaks = 60)
boxplot(caro$stepMean)

caro <- caro %>%
  mutate(static = stepMean < mean(stepMean, na.rm =TRUE)) #Assign boolean if the step-mean is below threshold (= mean of all stepmeans)

caro_filtered <- caro %>%
  filter(!static)
```

Task 3
```{r}
ggplot(caro, aes(x = E, y = N, colour = static), alpha = 0.5)+
  geom_path()+
  geom_point()+
  coord_equal()

```

Task 4

```{r}

rle_id <- function(vec){
  x <- rle(vec)$lengths
  as.factor(rep(seq_along(x), times=x))
  }


caro <- caro %>%
  mutate(
    segment_id = rle_id(static)
  )%>%
  
  group_by(segment_id)%>%
  
  mutate(
    segment_length = n(),
    segment_time = difftime(max(DatetimeUTC), min(DatetimeUTC))
  )%>%
  ungroup()
  
  
caro1 <- filter(caro, !static)

caro2 <- filter(caro1, segment_time > 300)
  
ggplot(caro1, aes(x = E, y = N, colour = segment_id), alpha = 0.5)+
  labs(title = " All Trajectories")+
  geom_path()+
  geom_point()+
  coord_fixed()

ggplot(caro2, aes(x = E, y = N, colour = segment_id), alpha = 0.5)+
  labs(title = "Trajectories over 5 minutes in length")+
  geom_path()+
  geom_point()+
  coord_fixed()
```
Task 5
```{r}

library(SimilarityMeasures)
library(patchwork)

pedestrian <- read_delim("data/pedestrian.txt", ",")

ggplot(data = pedestrian, mapping = aes(E, N))+
  geom_point(col = pedestrian$TrajID)+
  geom_path(col = pedestrian$TrajID)+
  facet_wrap(~TrajID, nrow = 2)+
  labs(title = "Different Trajectories")
  

```
Task 6

Tried piping commands for creating the matrix, but it wouldn't find the E and N columns when I used "append(E, N)" is there any sleeker way of doing this apart from creating a function?
```{r}

#Preparing the matrices
df <- filter(pedestrian, TrajID == 1)
traj <- append(df$E, df$N)
matrix1 <- matrix(traj, length(traj)/2)

df <- filter(pedestrian, TrajID == 2)
traj <- append(df$E, df$N)
matrix2 <- matrix(traj, length(traj)/2)

df <- filter(pedestrian, TrajID == 3)
traj <- append(df$E, df$N)
matrix3 <- matrix(traj, length(traj)/2)

df <- filter(pedestrian, TrajID == 4)
traj <- append(df$E, df$N)
matrix4 <- matrix(traj, length(traj)/2)

df <- filter(pedestrian, TrajID == 5)
traj <- append(df$E, df$N)
matrix5 <- matrix(traj, length(traj)/2)

df <- filter(pedestrian, TrajID == 6)
traj <- append(df$E, df$N)
matrix6 <- matrix(traj, length(traj)/2)

#Calculating Similarity Measures
dtw <- DTW(matrix1, matrix2, -1)%>%
  append(DTW(matrix1, matrix3, -1))%>%
  append(DTW(matrix1, matrix4, -1))%>%
  append(DTW(matrix1, matrix5, -1))%>%
  append(DTW(matrix1, matrix6, -1))

pd <- 10
edit_dist <- EditDist(matrix1, matrix2, pd)%>%
  append(EditDist(matrix1, matrix3, pd))%>%
  append(EditDist(matrix1, matrix4, pd))%>%
  append(EditDist(matrix1, matrix5, pd))%>%
  append(EditDist(matrix1, matrix6, pd))

frechet_dist <- Frechet(matrix1, matrix2)%>%
  append(Frechet(matrix1, matrix3))%>%
  append(Frechet(matrix1, matrix4))%>%
  append(Frechet(matrix1, matrix5))%>%
  append(Frechet(matrix1, matrix6))

lcss_dist <- LCSS(matrix1, matrix2, 2, 2, 0.5)%>%
  append(LCSS(matrix1, matrix3, 2, 2, 0.5))%>%
  append(LCSS(matrix1, matrix4, 2, 2, 0.5))%>%
  append(LCSS(matrix1, matrix5, 2, 2, 0.5))%>%
  append(LCSS(matrix1, matrix6, 2, 2, 0.5))
```

Plotting 

Something went wrong when trajectory 1 is compared with trajectory 2, but I'm a bit confused by my own code and don't know what went wrong :) 
```{r}
#creating a dataframe with all the distances
trajectories <- c("2","3","4","5","6")
distance_measures <- data.frame(trajectories, dtw, edit_dist, frechet_dist, lcss_dist)
 
p1 <- ggplot(distance_measures, aes(x=trajectories, y=dtw, fill = trajectories)) + geom_bar(stat="identity", show.legend = FALSE) + ggtitle('Distance Time Warping')
p2 <- ggplot(distance_measures, aes(x=trajectories, y=lcss_dist, fill = trajectories)) + geom_bar(stat="identity", show.legend = FALSE) + ggtitle('Longest Common Shared Segment')
p3 <- ggplot(distance_measures, aes(x=trajectories, y=edit_dist, fill = trajectories)) + geom_bar(stat="identity", show.legend = FALSE) + ggtitle("Edit Distance")
p4 <- ggplot(distance_measures, aes(x=trajectories, y=frechet_dist, fill = trajectories)) + geom_bar(stat="identity", show.legend = FALSE) + ggtitle('Frechet Distance')

wrapped <- wrap_plots(p1,p2,p3,p4)
wrapped + plot_annotation(
  title = 'Comparison of different Similarity Measures',
  subtitle = 'Trajectory 1 vs. Trajectory 2-6'
)

```
